wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1674161849.952009
    t:
      1:
      - 1
      - 41
      - 49
      - 50
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 50
      - 55
      - 63
      3:
      - 1
      - 23
      4: 3.10.4
      5: 0.13.8
      8:
      - 3
      - 5
