name: Docker Image CI

on:
  push:
    branches: [ publish ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "$" | docker login \
          -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker build . --file trainer.dockerfile \
          --tag docker.io/${{ secrets.DOCKER_HUB_REPOSITORY }}/trainer:$GITHUB_SHA
        docker push docker.io/${{ secrets.DOCKER_HUB_REPOSITORY }}/trainer:$GITHUB_SHA
